### ISSUE TITLE
20231004 Feedback

### ISSUE THREAD

**Issue by MisooKim2** [kims7186/CPP202309#1]
에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
- ERROR in challenge/week5/randomMax
    - Error: redefinition of 'value' [line 35]
        -  이유: 변수 선언이 두 번 이상 수행되었습니다
        -  해결: 변수 선언은 한 번만 하도록 수정해주세요
            - 34번 라인에서 범위기반 for 문에 있는  "int value"는 해당 for문 안에서 value를 사용하겠다고 선언된 상태입니다. 그러므로 35번 라인에서 int value에 int를 제거하시거나, 35번 라인을 지워주세요.

**Comment by kims7186** [comment]
변수 선언은 한 번만 하도록 수정 하였습니다. #1
