### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [kims7186/CPP202309#2]
### 없는 파일
- practice/week7/recommendation_base.cpp
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

### 없는 PDF 파일
- project/week6/tic_tac_toe.pdf
- project/week8/mud_game.pdf
	- 위 파일 이름이나 위치를 다시 확인하세요. 보고서 채점이 수행되지 않습니다.

### 에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
- ERROR in challenge/week3/math
    - Error: expected ';' after expression [line 25]
        - 세미콜론을 추가해주세요.

**Comment by kims7186** [comment]
#2 
1.없는 파일
practice/week7/recommendation_base.cpp
위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.
> 과제란의 파일경로로 작성해서 파일위치 조정했습니다. 

2.없는 PDF 파일
project/week8/mud_game.pdf
위 파일 이름이나 위치를 다시 확인하세요. 보고서 채점이 수행되지 않습니다.
>파일 열리지 않고, 이름이 상이해서 변경했습니다. 

3.에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
ERROR in challenge/week3/math
Error: expected ';' after expression [line 25]
> 세미콜론 추가했습니다
